# __Preprocesamiento de los datos__

In [4]:
import pandas as pd
import numpy as np

## Cargar datos

In [5]:
df1 = pd.read_excel('../data/Afluencia_2021.xlsx')
df2 = pd.read_excel('../data/Afluencia_2022.xlsx')
df3 = pd.read_excel('../data/Afluencia_2023.xlsx')
df4 = pd.read_excel('../data/Afluencia_2024.xlsx')
df5 = pd.read_excel('../data/Afluencia_2025.xlsx')

df_total = pd.concat([df1, df2, df3, df4, df5], ignore_index=True)
df_total

,Fecha,Linea,04:00:00,05:00:00,06:00:00,07:00:00,08:00:00,09:00:00,10:00:00,11:00:00,...,15:00:00,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,Total general (Número de pasajeros)
0,2021-01-01 00:00:00,LÍNEA A,NaN,3487.0,3405.0,2011.0,1148.0,974.0,888.0,1011.0,...,1833.0,2900.0,3269.0,3314.0,2273.0,1329.0,12.0,NaN,NaN,31911
1,2021-01-01 00:00:00,LÍNEA B,NaN,532.0,438.0,267.0,164.0,145.0,135.0,142.0,...,212.0,321.0,421.0,432.0,215.0,157.0,NaN,NaN,NaN,4050
2,2021-01-01 00:00:00,LÍNEA K,NaN,NaN,NaN,NaN,40.0,131.0,104.0,156.0,...,167.0,258.0,189.0,122.0,103.0,38.0,NaN,NaN,NaN,1714
3,2021-01-01 00:00:00,LÍNEA J,NaN,NaN,NaN,NaN,1.0,77.0,74.0,92.0,...,146.0,179.0,132.0,135.0,69.0,42.0,3.0,NaN,NaN,1256
4,2021-01-01 00:00:00,LÍNEA 1,NaN,614.0,590.0,355.0,240.0,217.0,198.0,231.0,...,394.0,579.0,624.0,574.0,399.0,231.0,17.0,NaN,NaN,6104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20220,2025-09-30 00:00:00,LÍNEA K,2430.0,2828.0,2543.0,2160.0,1852.0,1345.0,1111.0,1204.0,...,753.0,1026.0,860.0,624.0,525.0,559.0,270.0,100.0,NaN,23385
20221,2025-09-30 00:00:00,LÍNEA M,381.0,1056.0,931.0,711.0,452.0,364.0,303.0,352.0,...,494.0,659.0,659.0,1178.0,891.0,526.0,402.0,306.0,74.0,10881
20222,2025-09-30 00:00:00,LÍNEA O,265.0,1592.0,1723.0,1820.0,1195.0,1190.0,850.0,1091.0,...,1145.0,1529.0,1810.0,1231.0,1119.0,904.0,825.0,310.0,14.0,21785
20223,2025-09-30 00:00:00,LÍNEA P,1315.0,3172.0,2793.0,2575.0,1621.0,1065.0,735.0,987.0,...,708.0,874.0,979.0,625.0,482.0,579.0,386.0,157.0,3.0,21684
20224,2025-09-30 00:00:00,LÍNEA T-A,1444.0,4713.0,5166.0,4760.0,3479.0,2864.0,2348.0,2684.0,...,3242.0,4529.0,4096.0,5130.0,3291.0,2497.0,1847.0,1156.0,61.0,62053

In [6]:
df_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20225 entries, 0 to 20224
Data columns (total 23 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Fecha                                20225 non-null  object
 1   Linea                                20225 non-null  object
 2   04:00:00                             17109 non-null  float64
 3   05:00:00                             17186 non-null  float64
 4   06:00:00                             17190 non-null  float64
 5   07:00:00                             17204 non-null  float64
 6   08:00:00                             19301 non-null  float64
 7   09:00:00                             20177 non-null  float64
 8   10:00:00                             20169 non-null  float64
 9   11:00:00                             20160 non-null  float64
 10  12:00:00                             20166 non-null  float64
 11  13:00:00                             20160 non-null  float64
 12  14:00:00                             20150 non-null  float64
 13  15:00:00                             20131 non-null  float64
 14  16:00:00                             20138 non-null  float64
 15  17:00:00                             20137 non-null  float64
 16  18:00:00                             19049 non-null  float64
 17  19:00:00                             18686 non-null  float64
 18  20:00:00                             18685 non-null  float64
 19  21:00:00                             18681 non-null  float64
 20  22:00:00                             18502 non-null  float64
 21  23:00:00                             11751 non-null  float64
 22  Total general (Número de pasajeros)  20225 non-null  int64
dtypes: float64(20), int64(1), object(2)
memory usage: 3.5+ MB

## Limpiar datos

In [7]:
df_total.head(5)

,Fecha,Linea,04:00:00,05:00:00,06:00:00,07:00:00,08:00:00,09:00:00,10:00:00,11:00:00,...,15:00:00,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,Total general (Número de pasajeros)
0,2021-01-01 00:00:00,LÍNEA A,NaN,3487.0,3405.0,2011.0,1148.0,974.0,888.0,1011.0,...,1833.0,2900.0,3269.0,3314.0,2273.0,1329.0,12.0,NaN,NaN,31911
1,2021-01-01 00:00:00,LÍNEA B,NaN,532.0,438.0,267.0,164.0,145.0,135.0,142.0,...,212.0,321.0,421.0,432.0,215.0,157.0,NaN,NaN,NaN,4050
2,2021-01-01 00:00:00,LÍNEA K,NaN,NaN,NaN,NaN,40.0,131.0,104.0,156.0,...,167.0,258.0,189.0,122.0,103.0,38.0,NaN,NaN,NaN,1714
3,2021-01-01 00:00:00,LÍNEA J,NaN,NaN,NaN,NaN,1.0,77.0,74.0,92.0,...,146.0,179.0,132.0,135.0,69.0,42.0,3.0,NaN,NaN,1256
4,2021-01-01 00:00:00,LÍNEA 1,NaN,614.0,590.0,355.0,240.0,217.0,198.0,231.0,...,394.0,579.0,624.0,574.0,399.0,231.0,17.0,NaN,NaN,6104

In [9]:
# convertir valores nulos en cero
df_total.fillna(0, inplace=True)
df_total.head(5)

,Fecha,Linea,04:00:00,05:00:00,06:00:00,07:00:00,08:00:00,09:00:00,10:00:00,11:00:00,...,15:00:00,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,Total general (Número de pasajeros)
0,2021-01-01 00:00:00,LÍNEA A,0.0,3487.0,3405.0,2011.0,1148.0,974.0,888.0,1011.0,...,1833.0,2900.0,3269.0,3314.0,2273.0,1329.0,12.0,0.0,0.0,31911
1,2021-01-01 00:00:00,LÍNEA B,0.0,532.0,438.0,267.0,164.0,145.0,135.0,142.0,...,212.0,321.0,421.0,432.0,215.0,157.0,0.0,0.0,0.0,4050
2,2021-01-01 00:00:00,LÍNEA K,0.0,0.0,0.0,0.0,40.0,131.0,104.0,156.0,...,167.0,258.0,189.0,122.0,103.0,38.0,0.0,0.0,0.0,1714
3,2021-01-01 00:00:00,LÍNEA J,0.0,0.0,0.0,0.0,1.0,77.0,74.0,92.0,...,146.0,179.0,132.0,135.0,69.0,42.0,3.0,0.0,0.0,1256
4,2021-01-01 00:00:00,LÍNEA 1,0.0,614.0,590.0,355.0,240.0,217.0,198.0,231.0,...,394.0,579.0,624.0,574.0,399.0,231.0,17.0,0.0,0.0,6104

In [12]:
# convertir campos float a enteros
cols_float = df_total.select_dtypes(include='float').columns
df_total[cols_float] = df_total[cols_float].astype(int)
df_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20225 entries, 0 to 20224
Data columns (total 23 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Fecha                                20225 non-null  object
 1   Linea                                20225 non-null  object
 2   04:00:00                             20225 non-null  int64
 3   05:00:00                             20225 non-null  int64
 4   06:00:00                             20225 non-null  int64
 5   07:00:00                             20225 non-null  int64
 6   08:00:00                             20225 non-null  int64
 7   09:00:00                             20225 non-null  int64
 8   10:00:00                             20225 non-null  int64
 9   11:00:00                             20225 non-null  int64
 10  12:00:00                             20225 non-null  int64
 11  13:00:00                             20225 non-null  int64
 12  14:00:00                             20225 non-null  int64
 13  15:00:00                             20225 non-null  int64
 14  16:00:00                             20225 non-null  int64
 15  17:00:00                             20225 non-null  int64
 16  18:00:00                             20225 non-null  int64
 17  19:00:00                             20225 non-null  int64
 18  20:00:00                             20225 non-null  int64
 19  21:00:00                             20225 non-null  int64
 20  22:00:00                             20225 non-null  int64
 21  23:00:00                             20225 non-null  int64
 22  Total general (Número de pasajeros)  20225 non-null  int64
dtypes: int64(21), object(2)
memory usage: 3.5+ MB

In [15]:
# convertir campo Fecha a datetime
df_total['Fecha'] = pd.to_datetime(df_total['Fecha'], dayfirst=True)
df_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20225 entries, 0 to 20224
Data columns (total 23 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Fecha                                20225 non-null  datetime64[ns]
 1   Linea                                20225 non-null  object
 2   04:00:00                             20225 non-null  int64
 3   05:00:00                             20225 non-null  int64
 4   06:00:00                             20225 non-null  int64
 5   07:00:00                             20225 non-null  int64
 6   08:00:00                             20225 non-null  int64
 7   09:00:00                             20225 non-null  int64
 8   10:00:00                             20225 non-null  int64
 9   11:00:00                             20225 non-null  int64
 10  12:00:00                             20225 non-null  int64
 11  13:00:00                             20225 non-null  int64
 12  14:00:00                             20225 non-null  int64
 13  15:00:00                             20225 non-null  int64
 14  16:00:00                             20225 non-null  int64
 15  17:00:00                             20225 non-null  int64
 16  18:00:00                             20225 non-null  int64
 17  19:00:00                             20225 non-null  int64
 18  20:00:00                             20225 non-null  int64
 19  21:00:00                             20225 non-null  int64
 20  22:00:00                             20225 non-null  int64
 21  23:00:00                             20225 non-null  int64
 22  Total general (Número de pasajeros)  20225 non-null  int64
dtypes: datetime64[ns](1), int64(21), object(1)
memory usage: 3.5+ MB

In [17]:
df_total.head(5)

,Fecha,Linea,04:00:00,05:00:00,06:00:00,07:00:00,08:00:00,09:00:00,10:00:00,11:00:00,...,15:00:00,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,Total general (Número de pasajeros)
0,2021-01-01,LÍNEA A,0,3487,3405,2011,1148,974,888,1011,...,1833,2900,3269,3314,2273,1329,12,0,0,31911
1,2021-01-01,LÍNEA B,0,532,438,267,164,145,135,142,...,212,321,421,432,215,157,0,0,0,4050
2,2021-01-01,LÍNEA K,0,0,0,0,40,131,104,156,...,167,258,189,122,103,38,0,0,0,1714
3,2021-01-01,LÍNEA J,0,0,0,0,1,77,74,92,...,146,179,132,135,69,42,3,0,0,1256
4,2021-01-01,LÍNEA 1,0,614,590,355,240,217,198,231,...,394,579,624,574,399,231,17,0,0,6104

In [ ]:
# quitar la palabra Linea del campo Linea
df_total[]